Feature/#196-update-maven-enforcer-rule (#199)
* #192 Reduce maven log verbosity

* Fix windows build

* Cache sonar packages

* Upgrade dependencies

* Fix failing windows build: use ` as line continuation char for powershell

mvn install:install-file -Dfile="project-keeper.jar" \
    --batch-mode \
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.13-8\x64
ParserError: D:\a\_temp\8a28777c-ac7a-4537-a0a9-24d19f73912c.ps1:3
Line |
   3 |    --batch-mode \
     |      ~
     | Missing expression after unary operator '--'.

Error: Process completed with exit code 1.

* Increment version, update changelog

* Update doc/changes/changes_1.3.3.md

Co-authored-by: Muhammet Orazov <m.orazow@gmail.com>

* Run project-keeper:fix

* #196: Update required maven version to 3.6.3

* Update versions in maven templates

* Fix build on windows

Error:  Unknown lifecycle phase ".slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn".

Co-authored-by: Muhammet Orazov <m.orazow@gmail.com>